name: Deploy to EC2

on:
  push:
    branches:
      - main 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Backend Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/ictg_task-backend:latest ./backend
          docker push ${{ secrets.DOCKER_USERNAME }}/ictg_task-backend:latest

      - name: Build and Push Frontend Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/ictg_task-frontend:latest ./frontend
          docker push ${{ secrets.DOCKER_USERNAME }}/ictg_task-frontend:latest

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            # Stop and remove existing containers
            sudo docker stop backend frontend postgres_database || true
            sudo docker rm backend frontend postgres_database || true

            # Pull latest images
            sudo docker pull destinyobs/ictg_task-backend:latest
            sudo docker pull destinyobs/ictg_task-frontend:latest

            # Ensure network exists
            sudo docker network inspect devops-network >/dev/null 2>&1 || docker network create devops-network

            # Restart Database
            sudo docker run -d \
              --name postgres_database \
              --network devops-network \
              -e POSTGRES_USER=app \
              -e POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }} \
              -e POSTGRES_DB=ictg_db \
              -p 5432:5432 \
              postgres:latest

            # Wait for database to be ready
            until docker exec postgres_database pg_isready -U app; do
              echo "Waiting for PostgreSQL to be ready..."
              sleep 5
            done

            # Run Backend
            sudo docker run -d \
              --name backend \
              --network devops-network \
              -e DATABASE_URL="postgresql://app:${{ secrets.POSTGRES_PASSWORD }}@postgres_database:5432/ictg_db" \
              -p 8000:8000 \
              destinyobs/ictg_task-backend:latest

            # Run Frontend
            sudo docker run -d \
              --name frontend \
              --network devops-network \
              -p 5173:5173 \
              destinyobs/ictg_task-frontend:latest

            # Cleanup
            sudo docker system prune -af
